// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS-bKmEgIFUL1fWE9vRUnTVKu9x9K7UqM',
    appId: '1:134955677290:web:c429b20a6b1a8431543c13',
    messagingSenderId: '134955677290',
    projectId: 'myfluttermgovaward',
    authDomain: 'myfluttermgovaward.firebaseapp.com',
    databaseURL: 'https://myfluttermgovaward-default-rtdb.firebaseio.com',
    storageBucket: 'myfluttermgovaward.appspot.com',
    measurementId: 'G-T2NS3BQWG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezvoIIPNuZVALN5-HB8YkmvDnDk7Ki34',
    appId: '1:134955677290:android:372af7830b9110c3543c13',
    messagingSenderId: '134955677290',
    projectId: 'myfluttermgovaward',
    databaseURL: 'https://myfluttermgovaward-default-rtdb.firebaseio.com',
    storageBucket: 'myfluttermgovaward.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPlKG9GpiVRP7DMM_u1fcm4Zm7MenwCo',
    appId: '1:134955677290:ios:b8fb4769f0cfa276543c13',
    messagingSenderId: '134955677290',
    projectId: 'myfluttermgovaward',
    databaseURL: 'https://myfluttermgovaward-default-rtdb.firebaseio.com',
    storageBucket: 'myfluttermgovaward.appspot.com',
    iosBundleId: 'com.example.mgovaward',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFPlKG9GpiVRP7DMM_u1fcm4Zm7MenwCo',
    appId: '1:134955677290:ios:b8fb4769f0cfa276543c13',
    messagingSenderId: '134955677290',
    projectId: 'myfluttermgovaward',
    databaseURL: 'https://myfluttermgovaward-default-rtdb.firebaseio.com',
    storageBucket: 'myfluttermgovaward.appspot.com',
    iosBundleId: 'com.example.mgovaward',
  );
}
